apiVersion: apps/v1
kind: Deployment
metadata:
  name: node_app
  labels:
    app: node_app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: node_app 
  template:
    metadata:
      labels:
        app: node_app
    spec:
      containers:
        - name: node_app
          image: baluaddagatla/container_app_sample:latest # Replace with your Docker image
          ports:
            - containerPort: 3000 # Adjust the port as needed
          env:
            - name: NODE_ENV
              value: "production" # Set environment variables as needed