apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app
spec:
  serviceName: "node-app"
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: baluaddagatla/container_app_sample:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-session
              mountPath: /app/sessions  # Adjust to where your app stores session data
      volumes:
        - name: shared-session
          persistentVolumeClaim:
            claimName: hostpath
