apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: node-app 
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: baluaddagatla/container_app_sample:latest # Replace with your Docker image
          ports:
            - containerPort: 3000 # Adjust the port as needed
          env:
            - name: NODE_ENV
              value: "production" # Set environment variables as needed
      volume:
        - name: node-app-storage
          persistentVolumeClaim:
            claimName: my-pvc # Ensure this PVC is created in advance
      