apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: node-app 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: baluaddagatla/container_app_sample:1.0.31
          ports:
            - containerPort: 3000 # Adjust the port as needed
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:  
                configMapKeyRef:
                  name: env-config
                  key: REDIS_PORT
      readinessProbe:
        httpGet:
          path: /ready
          port: 3000 # Adjust the port as needed 
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 3000 # Adjust the port as needed  
        initialDelaySeconds: 15
        periodSeconds: 10 
      startupProbe:
        httpGet:
          path: /health
          port: 3000 # Adjust the port as needed
        initialDelaySeconds: 20
        periodSeconds: 10

              
