apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: dev
  labels:
    app: jenkins
    component: webserver
    environment: production
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---

