apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: argocd
  labels:
    app: nginx
    component: webserver
    environment: production
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
